import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Permanent_Marker } from 'next/font/google';

import "./globals.css";
import { Providers } from "./providers";

const permanentMarker = Permanent_Marker({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-permanent-marker',
});

const geist = Geist({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-geist',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable}`}
      >
        <Providers>
          
            {children}
        </Providers>
      </body>
    </html>
  );
}
