/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ComicMarketplace__factory } from "./ComicMarketplace__factory";
export { ComicNFT__factory } from "./ComicNFT__factory";
